name: Run Traffmonetizer Parallel

on:
  schedule:
    - cron: '0 */6 * * *'  # Jalan otomatis tiap 6 jam
  workflow_dispatch:       # Bisa dijalankan manual juga

jobs:
  run-traff:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
      max-parallel: 20

    steps:
      - name: Jalankan traffmonetizer ${{ matrix.instance }}
        run: |
          echo "Menjalankan instance ${{ matrix.instance }}"

          curl -O https://raw.githubusercontent.com/tiennm99/traffmonetizer/master/run.sh
          chmod +x run.sh

          sudo bash run.sh yxJ+/sZpOy5mP/VdagnR2kqgsa9o0krCw+Uc/XZnlgE= &

          # Tahan 6 jam biar job tetap hidup
          sleep 21600
