name: Run Max Docker on Free Tier

on:
  schedule:
    - cron: '*/5 * * * *'
    - cron: '* * * * *'  # setiap 1 menit
  workflow_dispatch:

jobs:
  run-wipter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,
                   11,12,13,14,15,16,17,18,19,20]
      max-parallel: 20

    steps:
      - name: Jalankan Docker Wipter ${{ matrix.instance }}
        run: |
          docker run -d \
            --name docker-wipter-${{ matrix.instance }} \
            -e WIPTER_EMAIL="vjguntur0+${{ matrix.instance }}@gmail.com" \
            -e WIPTER_PASSWORD="Wildan123@" \
            -e DISCORD_WEBHOOK_INTERVAL=300 \
            -e DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/1382948191137435688/emuut6Jky0wwLDH5lrHINxGLeZcFuKcOT2PycLcul1lW6fh-BjW24kdV7VbEtjafr45B" \
            -e VNC_PASS="123456" \
            -e VNC_PORT=$((5555 + ${{ matrix.instance }})) \
            -e NOVNC_PORT=$((6666 + ${{ matrix.instance }})) \
            -p $((5555 + ${{ matrix.instance }})):$((5555 + ${{ matrix.instance }})) \
            -p $((6666 + ${{ matrix.instance }})):$((6666 + ${{ matrix.instance }})) \
            --shm-size=2gb \
            ghcr.io/techroy23/docker-wipter:latest
