name: GetScreen Ubuntu (1M)

on:
  schedule:
    - cron: '* * * * *'  # setiap 1 menit
  workflow_dispatch:

jobs:
  build:
    name: InternetIncome
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 50
      fail-fast: false
      matrix:
        job: [1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git ca-certificates curl gnupg lsb-release unzip
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Download InternetIncome
        run: |
          wget -O main.zip https://github.com/gunturyogatama404/InternetIncome/archive/refs/heads/main.zip
          unzip -o main.zip

      - name: Run Reset Script
        working-directory: InternetIncome-main
        run: |
          sudo bash internetIncome.sh --start
